routes/web.php
<?php

use Illuminate\Support\Facades\{Route, Auth};

use App\Http\Controllers\{
    AboutController,
    CategoryController,
    ContactController,
    CourseController,
    HomeController,
    PolicyController,
    RazorpayController,
    SliderController
};
use App\Http\Livewire\Checkout;

Route::get('/', [HomeController::class, 'index'])->name('welcome');
Route::get('about', [HomeController::class, 'about'])->name('about');
Route::get('contact', [HomeController::class, 'contact'])->name('contact');


Auth::routes();

Route::post('contact', [ContactController::class, 'contact'])->name('contact');


Route::get('course-details/{course:slug}', [CourseController::class, 'courseDetail'])->name('course.details');
Route::get('my-courses', [CourseController::class, 'userCourse'])->name('user.courses');

Route::get('terms-and-conditions', [HomeController::class, 'terms'])->name('terms');

Route::middleware('auth')->group(function () {

    Route::get('checkout/{course:slug}', [RazorpayController::class, 'index'])->name('razorpay.index');
    Route::post('checkout/{course:slug}', [RazorpayController::class, 'store'])->name('razorpay.store');

    Route::get('show', [RazorpayController::class, 'pdf_show'])->name('razorpay.show');

    Route::middleware('admin')->prefix('admin')->group(function () {
        Route::get('home', [HomeController::class, 'home'])->name('home');
        Route::post('about-image-slider', [AboutController::class, 'aboutSliderStore'])->name('about.slider.store');
        Route::delete('about-image-slider/{id}/delete', [AboutController::class, 'aboutSliderDestroy'])->name('about.slider.destroy');

        Route::get('about-image', [AboutController::class, 'index'])->name('about.index');
        Route::post('about-image', [AboutController::class, 'store'])->name('about.store');
        Route::delete('about-image/{id}/delete', [AboutController::class, 'destroy'])->name('about.destroy');

        Route::get('slider-image', [SliderController::class, 'index'])->name('slider.index');
        Route::post('slider-image', [SliderController::class, 'store'])->name('slider.store');
        Route::delete('slider-image/{id}/delete', [SliderController::class, 'destroy'])->name('slider.destroy');

        Route::get('category', [CategoryController::class, 'index'])->name('category.index');
        Route::post('category', [CategoryController::class, 'store'])->name('category.store');
        Route::get('category/create', [CategoryController::class, 'create'])->name('category.create');
        Route::get('category/{category:id}/edit', [CategoryController::class, 'edit'])->name('category.edit');
        Route::put('category/{category:slug}', [CategoryController::class, 'update'])->name('category.update');
        Route::delete('category/{category:slug}/delete', [CategoryController::class, 'destroy'])->name('category.destroy');

        Route::resource('course', CourseController::class);

        Route::get('course-users/{id}', [CourseController::class, 'courseUsers'])->name('course.users');
        Route::delete('course-user/{id}/delete', [CourseController::class, 'courseUsersDelete'])->name('course.user.destroy');

        Route::post('course-services', [CourseController::class, 'serviceStore'])->name('course.service');
        Route::delete('course-services/{service:id}/delete', [CourseController::class, 'serviceDelete'])->name('service.destroy');

        Route::delete('contact/{id}/delete', [ContactController::class, 'destroy'])->name('contact.destroy');

        Route::get('terms', [PolicyController::class, 'index'])->name('policy.index');
        Route::post('terms', [PolicyController::class, 'store'])->name('policy.store');
        Route::get('terms/create', [PolicyController::class, 'create'])->name('policy.create');
        Route::get('terms/{policy:id}/edit', [PolicyController::class, 'edit'])->name('policy.edit');
        Route::put('terms/{policy:id}', [PolicyController::class, 'update'])->name('policy.update');
        Route::delete('terms/{policy:id}/delete', [PolicyController::class, 'destroy'])->name('policy.destroy');
    });
});

resources/views/Admin/Courses/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row mb-2">
            <div class="col-md-10">
                <div style="display: flex;justify-content: flex-end">
                    <a href="{{ route('course.index') }}" class="btn btn-primary">
                        Back
                    </a>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                @endif
                <div class="card">
                    <div class="card-header">{{ __('Add Category') }}</div>
                    <form class="card-body" action="{{ route('course.store') }}" method="post"
                        enctype="multipart/form-data">
                        @csrf
                        <div class="mb-3">
                            <label for="course_title" class="form-label">Enter Course Title:</label>
                            <input type="text" class="form-control" id="course_title" name="title">
                            @error('title')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="category_id" class="form-label">Enter Category:</label>
                            <select class="form-control" id="category_id" name="category_id" id="">
                                <option value="">Select</option>
                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                                @endforeach
                            </select>
                            @error('category_id')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="excerpt" class="form-label">Enter Excerpt:</label>
                            <input type="text" class="form-control" id="excerpt" name="excerpt">
                            @error('excerpt')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="category_desc" class="form-label">Description</label>
                            <textarea class="form-control" id="category_desc" rows="3" name="description"></textarea>
                            @error('description')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="category_price" class="form-label">Enter Price:</label>
                            <input type="text" class="form-control" id="category_price" name="price">
                            @error('price')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="category_discount_price" class="form-label">Enter Discount Price:</label>
                            <input type="text" class="form-control" id="category_discount_price" name="discount_price">
                            @error('discount_price')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="batch_start_at" class="form-label">Batch Start At:</label>
                            <input type="date" class="form-control" id="batch_start_at" name="batch_start_at">
                            @error('batch_start_at')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="thumbnail" class="form-label">Enter Thumbnail:</label>
                            <input type="file" class="form-control" id="thumbnail" name="thumbnail">
                            @error('thumbnail')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="demo_video" class="form-label">Choose Video:</label>
                            <input type="file" class="form-control" id="demo_video" name="demo_video">
                            @error('demo_video')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <button class="btn btn-primary">Create</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/Admin/Courses/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row mb-2">
            <div class="col-md-10">
                <div style="display: flex;justify-content: flex-end">
                    <a href="{{ route('course.index') }}" class="btn btn-primary">
                        Back
                    </a>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                @endif
                <div class="card">
                    <div class="card-header">{{ __('Edit Category') }}</div>
                    <form class="card-body" action="{{ route('course.update', $course->id) }}" method="post"
                        enctype="multipart/form-data">
                        @csrf
                        @method('put')
                        <div class="mb-3">
                            <label for="course_title" class="form-label">Enter Course Title:</label>
                            <input type="text" class="form-control" id="course_title" name="title"
                                value="{{ $course->title }}">
                            @error('title')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="category_id" class="form-label">Enter Category:</label>
                            <select class="form-control" id="category_id" name="category_id" id="">
                                <option value="" disabled>Select</option>
                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                                @endforeach
                            </select>
                            @error('excerpt')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="excerpt" class="form-label">Enter Excerpt:</label>
                            <input type="text" class="form-control" id="excerpt" name="excerpt"
                                value="{{ $course->excerpt }}">
                            @error('excerpt')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="category_desc" class="form-label">Description</label>
                            <textarea class="form-control" id="category_desc" rows="3"
                                name="description">{{ $course->description }}</textarea>
                        </div>
                        <div class="mb-3">
                            <label for="category_price" class="form-label">Enter Price:</label>
                            <input type="text" class="form-control" id="category_price" name="price"
                                value="{{ $course->price / 100 }}">
                            @error('price')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="category_discount_price" class="form-label">Enter Discount Price:</label>
                            <input type="text" class="form-control" id="category_discount_price" name="discount_price"
                                value="{{ $course->discount_price / 100 }}">
                            @error('discount_price')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="batch_start_at" class="form-label">Batch Start At:
                                {{ $course->batch_start_at->format('d M Y') }}(current date value)</label>
                            <input type="date" class="form-control" id="batch_start_at" name="batch_start_at"
                                value="{{ $course->batch_start_at }}">
                            @error('batch_start_at')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="thumbnail" class="form-label">Enter Thumbnail:</label>
                            <input type="file" class="form-control" id="thumbnail" name="thumbnail">
                            @error('thumbnail')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="mb-3">
                            <label for="demo_video" class="form-label">Choose Video:</label>
                            <input type="file" class="form-control" id="demo_video" name="demo_video">
                            @error('name')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <button class="btn btn-primary">Update</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Add Services') }}</div>
                    <form class="card-body" action="{{ route('course.service') }}" method="post">
                        @csrf
                        <input type="hidden" name="course_id" value="{{ $course->id }}">
                        <div class="mb-3">
                            <label for="services" class="form-label">Enter Service:</label>
                            <input type="text" class="form-control" id="services" name="services">
                            @error('services')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <button class="btn btn-primary">Add</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="row mt-4 justify-content-center">
            <div class="col-md-8">
                <table class="table">
                    <thead class="table-dark">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Service</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($course->services as $service)
                            <tr>
                                <th scope="row">{{ $loop->iteration }}</th>
                                <th>{{ $service->services }}</th>
                                <td class="d-flex justify-content-center">
                                    <form action="{{ route('service.destroy', $service->id) }}" method="post">
                                        @csrf
                                        @method('delete')
                                        <button class="btn btn-danger">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/Admin/Courses/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        @if (session('status'))
            <div class="alert alert-success" role="alert">
                {{ session('status') }}
            </div>
        @endif
        <div class="row">
            <div class="col-md-10">
                <div style="display: flex;justify-content: flex-end">
                    <a href="{{ route('course.create') }}" class="btn btn-primary">
                        Add Courses
                    </a>
                </div>
            </div>
        </div>
        <div class="row mt-4 justify-content-center">
            <div class="col-md-9">
                <table class="table">
                    <thead class="table-dark">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Thumbnail</th>
                            <th scope="col">Title</th>
                            <th scope="col">Category</th>
                            <th scope="col">Price</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($courses as $course)
                            <tr>
                                <th scope="row">{{ $loop->iteration }}</th>
                                <th><img src="{{ asset('storage/' . $course->thumbnail) }}" width="100px" alt=""></th>
                                <th>{{ $course->title }}</th>
                                <th>{{ $course->category->name }}</th>
                                <th>Rs. {{ $course->price / 100 }} /-</th>
                                <td class="d-flex justify-content-center">
                                    <a href="{{ route('course.users', $course->id) }}"
                                        class="btn btn-warning mr-2 text-white">Interns</a>
                                    <a href="{{ route('course.edit', $course->id) }}" class="btn btn-info mr-2">Edit</a>
                                    <form action="{{ route('course.destroy', $course->id) }}" method="post">
                                        @csrf
                                        @method('delete')
                                        <button class="btn btn-danger">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection